# Generated by Django 5.2.13 on 2026-05-14 12:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('COACH', 'Coach'), ('ATHLETE', 'Athlete'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('onboarding_step', models.PositiveSmallIntegerField(default=1)),
                ('is_onboarding_finished', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('primary_goal', models.CharField(choices=[('ENDURANCE', 'Ultra Endurance'), ('SPEED', 'Raw Speed'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('max_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weekly_volume', models.CharField(choices=[('LOW', '0-5 Hours'), ('MID', '5-12 Hours'), ('HIGH', '12+ Hours'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('discipline', models.CharField(choices=[('RUNNING', 'Running / Track'), ('CYCLING', 'Road / MTB Cycling'), ('TRIATHLON', 'Triathlon / Ironman'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('sensors', models.JSONField(blank=True, default=list)),
                ('strava_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('strava_access_token', models.TextField(blank=True, null=True)),
                ('strava_refresh_token', models.TextField(blank=True, null=True)),
                ('strava_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('strava_raw_profile', models.JSONField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
