# Generated by Django 5.2.13 on 2026-05-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_heart_rate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_goal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sensors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekly_volume',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
