# Generated by Django 5.2.13 on 2026-05-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_age_remove_user_discipline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='strava_raw_profile',
        ),
    ]
