# Generated by Django 5.2.3 on 2026-05-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_strava_raw_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='strava_raw_profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
