# Generated by Django 5.2.3 on 2026-07-06 20:17

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_strava_raw_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. No spaces allowed.', max_length=150, unique=True, validators=[apps.accounts.models.CustomUsernameValidator()], verbose_name='username'),
        ),
    ]
