# Generated by Django 5.2.13 on 2026-07-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COACH', 'Coach'), ('ATHLETE', 'Athlete'), ('NONE', 'None')], default='ATHLETE', max_length=10),
        ),
    ]
