# Generated by Django 5.2.13 on 2026-05-16 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0002_remove_squad_athletes_squadmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='athletes',
            field=models.ManyToManyField(blank=True, related_name='squads', through='squads.SquadMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
