# Generated by Django 5.2.13 on 2026-05-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={},
        ),
        migrations.RemoveField(
            model_name='mission',
            name='scheduled_time',
        ),
        migrations.AlterField(
            model_name='mission',
            name='scheduled_date',
            field=models.DateTimeField(),
        ),
    ]
