# Generated by Django 5.2.3 on 2026-05-16 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_strava_id'),
        ('missions', '0002_alter_mission_options_remove_mission_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='satisfying_activity',
            field=models.ForeignKey(blank=True, help_text='The activity that successfully completed this mission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfied_missions', to='activities.activity'),
        ),
    ]
