# Generated by Django 5.2.13 on 2026-05-14 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField(unique=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(max_length=50)),
                ('sport_type', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('moving_time', models.PositiveIntegerField()),
                ('elapsed_time', models.PositiveIntegerField()),
                ('total_elevation_gain', models.FloatField()),
                ('elev_high', models.FloatField(blank=True, null=True)),
                ('elev_low', models.FloatField(blank=True, null=True)),
                ('average_speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('average_cadence', models.FloatField(blank=True, null=True)),
                ('average_temp', models.IntegerField(blank=True, null=True)),
                ('average_watts', models.FloatField(blank=True, null=True)),
                ('weighted_average_watts', models.FloatField(blank=True, null=True)),
                ('max_watts', models.FloatField(blank=True, null=True)),
                ('kilojoules', models.FloatField(blank=True, null=True)),
                ('device_watts', models.BooleanField(default=False)),
                ('has_heartrate', models.BooleanField(default=False)),
                ('average_heartrate', models.FloatField(blank=True, null=True)),
                ('max_heartrate', models.FloatField(blank=True, null=True)),
                ('suffer_score', models.IntegerField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('start_date_local', models.DateTimeField()),
                ('timezone', models.CharField(max_length=100)),
                ('utc_offset', models.IntegerField()),
                ('start_latlng', models.JSONField(blank=True, null=True)),
                ('end_latlng', models.JSONField(blank=True, null=True)),
                ('map_polyline', models.TextField(blank=True, null=True)),
                ('summary_polyline', models.TextField(blank=True, null=True)),
                ('achievement_count', models.IntegerField(default=0)),
                ('kudos_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('athlete_count', models.IntegerField(default=1)),
                ('photo_count', models.IntegerField(default=0)),
                ('total_photo_count', models.IntegerField(default=0)),
                ('trainer', models.BooleanField(default=False)),
                ('commute', models.BooleanField(default=False)),
                ('manual', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('gear_id', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-start_date'],
            },
        ),
    ]
