# Generated by Django 5.2.13 on 2026-05-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_raw_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='athlete_count',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='commute',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='flagged',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='gear_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='kudos_count',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='manual',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='photo_count',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='private',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_date_local',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='total_photo_count',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='utc_offset',
        ),
    ]
