# Generated by Django 5.2.13 on 2026-05-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_athlete_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='strava_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
